services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: qr-generator-api
    ports:
      - "8080:8080"
    networks:
      - qr-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: qr-generator-frontend
    ports:
      - "3000:80"
    networks:
      - qr-net

networks:
  qr-net:
    driver: bridge
