FROM golang:1.21 AS build

WORKDIR /app

COPY qr-generator-api/go.mod qr-generator-api/go.sum ./
RUN go mod download

COPY qr-generator-api/ ./
RUN go build -o server

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /app/server .

EXPOSE 8080
CMD ["./server"]
