FROM node:18 AS build

WORKDIR /app
COPY qr-generator-frontend/ ./

RUN npm install
RUN npm run build

# Сервер на nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Удаляем дефолтный конфиг
RUN rm /etc/nginx/conf.d/default.conf

# Добавляем свой
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
